### ISSUE TITLE
Add the xk6 label to the repository

### ISSUE THREAD

**Issue by simonaronsson** [olvod/xk6-pubsub#1]
Hi,

We're so excited to see that you've built an xk6 extension for sending data over Google Pub/Sub. If you don't mind, it would be great if you could add the `xk6` label to the repository so that it is visible for other users of xk6 as well when browsing https://github.com/topic/xk6.

Thanks a bunch,
Simme & the k6 team

**Comment by olvod** [comment]
Hi,

Done.
